language: java

deploy:
  provider: heroku
  api_key:
    secure: SmpXmtyUdnUm93+6BJWu4EaiuoH4t1SsqvOooay0BsyHyGpcOzcYyEiq8Yd1L1BJm6MVSys4ZvERMzW7xU9sl8if5mMGoDgEQ7LAV0YyXQKrbr80xhCU1qKKzOmGSI4goTAM71ndXJ3Y7JZ1qGix3VWTpifmf1RnouWl0CtOBFPwS5qwKGCwAhGhnP3qMocQ1sV4XAL39BCLQCPiegUAOmBO7MEOBleFDL3k1ROv6llt87MF1ZMuJloE2it6QK4uqMOh6/rCQ+f3pNeVoY4VsFnoHz69KhrxUp6aayWFCIOqaczauYhwH4hAEysdTC4O1cpKy6eI3DrF52RNsCBtiucSTVPLxPj8AyxWiC5BS6KXADZHxCF6V2m8NkAV1DyiWfnprKO5ZXenj23xHHjocY8P2Karuvr4lpZD8nfZL0Dr0lCjE8yT0zku6/R55j5HZtTIlLux3IlHiNFgR4sxRJ1kVDkBymE6X2OEiHRv+Sh2GjKFLxAawFEbgC1t8kTvlLPESW3vtAP55aUy88F6JEkL59EKHrRdmSuz1efcyN7KgudwX/UVYO8MgcYziT4yND+/oZX4Blrw1hFwfsITdSI1tEGUJj0L7XCec1kFppQKQ88mWtV33vDsdWr8XdPuUbAGDiEVnuGpUfKeBuyyb3SAef9BuFccvJr2/lXvVyE=
  app: todo-workshop-wvu
  on:
    repo: bhorn1/wvu-workshop
    branch: css-addition
